package com.trainingsapp.chrisals.dyel20.core;

/**
 * Created by chris.als on 09.03.17.
 */

public class ExerciseNames {
    public static final String[] EXERCISE_NAMES = {
        "Crunch",
        "Resisted Crunch",
        "Inclined Crunch with Feet Attached",
        "Crunch with Leg Curl",
        "Sit-Up with Feet Attached",
        "Sit-Up with Cable",
        "Trunk Rotation",
        "Jacknife Sit-Up",
        "High Leg Pull-In",
        "Low Leg Pull-In",
        "Side Plank",
        "Hyperextension",
        "Row",
        "Crossover Row",
        "Kneeling Row",
        "Row with Hyperextension",
        "Back Fly",
        "Rotating Back Fly",
        "Prone Back Fly",
        "Back Fly with Leg Curl",
        "Lateral Pulldown",
        "Pulldown with Squat with Elbows Flexed",
        "Lateral Pulldown with Squat",
        "Pull-Up",
        "Chest Press",
        "Close-Grip Chest Press",
        "Wide-Grip Chest Press",
        "Incline Push Up",
        "Chest Fly",
        "Incline Chest Fly",
        "Decline Chest Fly",
        "Lateral Chest Fly",
        "Pullover",
        "Pullover with Crunch",
        "Pullover with Twisting Crunch",
        "Pullover with Squat",
        "Single Leg Pullover with Squat",
        "Leg Curl",
        "Reverse Leg Curl",
        "Squat",
        "Wide Squat",
        "Single-Leg Squat",
        "Single-Leg Squat On Side",
        "Single-Leg Squat Kneeling",
        "Jumping Squat",
        "Twisting Squat",
        "Jumping and Twisting Squat",
        "Front Lunge",
        "Hip Extension with Knee Stabilized",
        "Hip Abduction",
        "Hip Adduction",
        "Calf Raise",
        "Shoulder Press",
        "Upright Row",
        "Upright Row with Hyperextension",
        "Upright Row with Leg Curl",
        "Lateral Deltoid Raise",
        "Front Deltoid Raise",
        "Wide Grip Front Deltoid Raise",
        "Front Deltoid Raise with Supination Grip",
        "Lying Front Deltoid Raise",
        "Front Deltoid Raise with Leg Curl",
        "Shoulder Extension",
        "Shoulder Extension with Hyperextension",
        "Shoulder Extension with Leg Curl",
        "Lateral Arm Pull",
        "Biceps Curl",
        "Lateral Single-Arm Biceps Curl",
        "Lying Biceps Curl",
        "Biceps Curl with Crunching",
        "Biceps Curl with Hyperextension",
        "Biceps Curl with Leg Curl",
        "Chin-Up",
        "Triceps Extension",
        "Prone Triceps Extension",
        "Kneeling Triceps Extension",
        "Lateral Single-Arm Triceps Extension"
    };
}
